# Generated by Django 6.0 on 2026-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('TECHNICIAN', 'Technician')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OWNER')), fields=('dealership',), name='uniq_owner_per_dealership'),
        ),
    ]
