"""Seed a large, realistic Indian-market demo inventory (data-only).

Adds ~150 real Indian-market vehicles to an EXISTING dealership using the
existing Vehicle model only. Safe to run multiple times: rows are matched on
the existing ``uniq_vehicle_inventory`` constraint fields
(dealership, brand, model, variant, manufacturing_year) and never modified.

Usage:
    python manage.py seed_demo_vehicles --dealership-id 1
"""

from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError

from apps.core.models import Dealership, Vehicle

# (brand, model, variant, year, fuel, transmission, seats, price, stock, note)
# Descriptions are derived from the note plus supported inventory attributes
# only (model / variant / fuel / transmission / seating / year).
DEMO_VEHICLES = [
    # ---------------- Maruti Suzuki (20) ----------------
    {"brand": "Maruti Suzuki", "model": "Alto K10", "variant": "STD", "manufacturing_year": 2022, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("415000.00"), "stock_quantity": 0, "description": "Alto K10 STD 2022, petrol manual, 5 seats. Entry-level hatchback, ideal first car for city use."},
    {"brand": "Maruti Suzuki", "model": "Alto K10", "variant": "STD", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("432000.00"), "stock_quantity": 4, "description": "Alto K10 STD 2023, petrol manual, 5 seats. Light, easy to drive hatchback for daily city commuting."},
    {"brand": "Maruti Suzuki", "model": "Alto K10", "variant": "VXi", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("525000.00"), "stock_quantity": 5, "description": "Alto K10 VXi 2024, petrol manual, 5 seats. Mid-trim hatchback with power steering and front power windows."},
    {"brand": "Maruti Suzuki", "model": "Alto K10", "variant": "VXi AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("575000.00"), "stock_quantity": 3, "description": "Alto K10 VXi AMT 2024, petrol automated-manual, 5 seats. Clutch-free driving for congested city traffic."},
    {"brand": "Maruti Suzuki", "model": "Alto K10", "variant": "LXi CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("610000.00"), "stock_quantity": 2, "description": "Alto K10 LXi CNG 2024, factory-fitted CNG manual, 5 seats. Very low running cost for high daily usage."},
    {"brand": "Maruti Suzuki", "model": "S-Presso", "variant": "LXi", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("485000.00"), "stock_quantity": 3, "description": "S-Presso LXi 2023, petrol manual, 5 seats. Tall micro-SUV stance with easy ingress and city agility."},
    {"brand": "Maruti Suzuki", "model": "S-Presso", "variant": "VXi AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("615000.00"), "stock_quantity": 2, "description": "S-Presso VXi AMT 2024, petrol automated-manual, 5 seats. High-seating hatchback with effortless automatic shifts."},
    {"brand": "Maruti Suzuki", "model": "Celerio", "variant": "LXi", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("555000.00"), "stock_quantity": 3, "description": "Celerio LXi 2023, petrol manual, 5 seats. Compact family hatchback known for fuel-efficient city driving."},
    {"brand": "Maruti Suzuki", "model": "Celerio", "variant": "ZXi AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("740000.00"), "stock_quantity": 2, "description": "Celerio ZXi AMT 2024, petrol automated-manual, 5 seats. Top-trim hatchback with touchscreen and auto gearbox."},
    {"brand": "Maruti Suzuki", "model": "Celerio", "variant": "VXi CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("730000.00"), "stock_quantity": 2, "description": "Celerio VXi CNG 2024, factory-fitted CNG manual, 5 seats. Economical hatchback for long daily commutes."},
    {"brand": "Maruti Suzuki", "model": "Dzire", "variant": "VXi", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 4, "description": "Dzire VXi 2024, petrol manual, 5 seats. Compact sedan with a usable boot for family and fleet use."},
    {"brand": "Maruti Suzuki", "model": "Dzire", "variant": "ZXi AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("965000.00"), "stock_quantity": 3, "description": "Dzire ZXi AMT 2024, petrol automated-manual, 5 seats. Feature-rich compact sedan with automatic convenience."},
    {"brand": "Maruti Suzuki", "model": "Dzire", "variant": "VXi CNG", "manufacturing_year": 2023, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("910000.00"), "stock_quantity": 2, "description": "Dzire VXi CNG 2023, factory-fitted CNG manual, 5 seats. Low-cost compact sedan for heavy running."},
    {"brand": "Maruti Suzuki", "model": "Baleno", "variant": "Sigma", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("695000.00"), "stock_quantity": 3, "description": "Baleno Sigma 2023, petrol manual, 5 seats. Spacious premium hatchback with a refined cabin."},
    {"brand": "Maruti Suzuki", "model": "Baleno", "variant": "Delta", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("785000.00"), "stock_quantity": 4, "description": "Baleno Delta 2024, petrol manual, 5 seats. Popular premium hatchback with touchscreen and steering controls."},
    {"brand": "Maruti Suzuki", "model": "Baleno", "variant": "Zeta AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("945000.00"), "stock_quantity": 3, "description": "Baleno Zeta AMT 2024, petrol automated-manual, 5 seats. Well-equipped hatchback with automatic ease."},
    {"brand": "Maruti Suzuki", "model": "Baleno", "variant": "Alpha AMT", "manufacturing_year": 2025, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("1025000.00"), "stock_quantity": 2, "description": "Baleno Alpha AMT 2025, petrol automated-manual, 5 seats. Flagship hatchback trim with all comfort features."},
    {"brand": "Maruti Suzuki", "model": "Fronx", "variant": "Delta+", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("920000.00"), "stock_quantity": 3, "description": "Fronx Delta+ 2024, petrol manual, 5 seats. Coupe-styled crossover with a commanding driving position."},
    {"brand": "Maruti Suzuki", "model": "Ertiga", "variant": "VXi", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1045000.00"), "stock_quantity": 3, "description": "Ertiga VXi 2024, petrol manual, 7 seats. Practical family MPV with flexible seating for seven."},
    {"brand": "Maruti Suzuki", "model": "Ertiga", "variant": "VXi CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1140000.00"), "stock_quantity": 2, "description": "Ertiga VXi CNG 2024, factory-fitted CNG manual, 7 seats. Seven-seat MPV with very low running cost."},
    # ---------------- Hyundai (18) ----------------
    {"brand": "Hyundai", "model": "Grand i10 Nios", "variant": "Era", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("595000.00"), "stock_quantity": 3, "description": "Grand i10 Nios Era 2023, petrol manual, 5 seats. Compact hatchback with a smooth engine and roomy cabin."},
    {"brand": "Hyundai", "model": "Grand i10 Nios", "variant": "Sportz CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("810000.00"), "stock_quantity": 2, "description": "Grand i10 Nios Sportz CNG 2024, factory-fitted CNG manual, 5 seats. Feature-loaded hatchback with low fuel bills."},
    {"brand": "Hyundai", "model": "i20", "variant": "Magna", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 4, "description": "i20 Magna 2024, petrol manual, 5 seats. Premium hatchback with sharp styling and a spacious interior."},
    {"brand": "Hyundai", "model": "i20", "variant": "Asta CVT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1095000.00"), "stock_quantity": 2, "description": "i20 Asta CVT 2024, petrol continuously-variable automatic, 5 seats. Smooth top-trim hatchback for city comfort."},
    {"brand": "Hyundai", "model": "Exter", "variant": "SX", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("835000.00"), "stock_quantity": 3, "description": "Exter SX 2023, petrol manual, 5 seats. Micro-SUV with high seating and a feature-packed cabin."},
    {"brand": "Hyundai", "model": "Exter", "variant": "SX AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("965000.00"), "stock_quantity": 2, "description": "Exter SX AMT 2024, petrol automated-manual, 5 seats. Tall micro-SUV with automatic convenience."},
    {"brand": "Hyundai", "model": "Exter", "variant": "S CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("885000.00"), "stock_quantity": 2, "description": "Exter S CNG 2024, factory-fitted CNG manual, 5 seats. Micro-SUV with economical dual-fuel running."},
    {"brand": "Hyundai", "model": "Aura", "variant": "S", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("725000.00"), "stock_quantity": 3, "description": "Aura S 2023, petrol manual, 5 seats. Compact sedan with comfortable rear seating and a decent boot."},
    {"brand": "Hyundai", "model": "Aura", "variant": "SX+ AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("895000.00"), "stock_quantity": 2, "description": "Aura SX+ AMT 2024, petrol automated-manual, 5 seats. Top compact-sedan trim with automatic gearbox."},
    {"brand": "Hyundai", "model": "Aura", "variant": "E CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("760000.00"), "stock_quantity": 2, "description": "Aura E CNG 2024, factory-fitted CNG manual, 5 seats. Budget compact sedan with very low running cost."},
    {"brand": "Hyundai", "model": "Venue", "variant": "E", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 2, "description": "Venue E 2023, petrol manual, 5 seats. Entry compact SUV with a tall stance and practical cabin."},
    {"brand": "Hyundai", "model": "Venue", "variant": "S(O)", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1095000.00"), "stock_quantity": 3, "description": "Venue S(O) 2024, petrol manual, 5 seats. Well-equipped compact SUV with sunroof and connected features."},
    {"brand": "Hyundai", "model": "Venue", "variant": "SX(O) DCT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1340000.00"), "stock_quantity": 2, "description": "Venue SX(O) DCT 2024, petrol dual-clutch automatic, 5 seats. Turbo compact SUV with quick automatic shifts."},
    {"brand": "Hyundai", "model": "Venue", "variant": "SX CRDi", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1290000.00"), "stock_quantity": 2, "description": "Venue SX CRDi 2024, diesel manual, 5 seats. Torque-rich compact SUV suited to highway touring."},
    {"brand": "Hyundai", "model": "Creta", "variant": "E", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1105000.00"), "stock_quantity": 2, "description": "Creta E 2023, petrol manual, 5 seats. Base trim of the popular compact SUV with a spacious cabin."},
    {"brand": "Hyundai", "model": "Creta", "variant": "SX(O) CVT", "manufacturing_year": 2025, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1875000.00"), "stock_quantity": 0, "description": "Creta SX(O) CVT 2025, petrol continuously-variable automatic, 5 seats. Flagship compact SUV, currently out of stock."},
    {"brand": "Hyundai", "model": "Creta", "variant": "SX Diesel AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1950000.00"), "stock_quantity": 2, "description": "Creta SX Diesel AT 2024, diesel automatic, 5 seats. Long-distance compact SUV with an easy torque-converter auto."},
    {"brand": "Hyundai", "model": "Alcazar", "variant": "Prestige", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("2140000.00"), "stock_quantity": 2, "description": "Alcazar Prestige 2024, diesel automatic, 7 seats. Three-row family SUV with captain-seat comfort."},
    # ---------------- Tata (22) ----------------
    {"brand": "Tata", "model": "Tiago", "variant": "XE", "manufacturing_year": 2021, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("495000.00"), "stock_quantity": 0, "description": "Tiago XE 2021, petrol manual, 5 seats. Sturdy entry hatchback, currently out of stock."},
    {"brand": "Tata", "model": "Tiago", "variant": "XT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("685000.00"), "stock_quantity": 4, "description": "Tiago XT 2024, petrol manual, 5 seats. Solid-build hatchback with a comfortable ride."},
    {"brand": "Tata", "model": "Tiago", "variant": "XZ+ AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("845000.00"), "stock_quantity": 2, "description": "Tiago XZ+ AMT 2024, petrol automated-manual, 5 seats. Top hatchback trim with automatic convenience."},
    {"brand": "Tata", "model": "Tiago", "variant": "XT CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 3, "description": "Tiago XT CNG 2024, factory-fitted CNG manual, 5 seats. Economical hatchback for daily commutes."},
    {"brand": "Tata", "model": "Tigor", "variant": "XM", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("735000.00"), "stock_quantity": 2, "description": "Tigor XM 2023, petrol manual, 5 seats. Compact sedan with a strong body shell and usable boot."},
    {"brand": "Tata", "model": "Tigor", "variant": "XZ+ CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("945000.00"), "stock_quantity": 2, "description": "Tigor XZ+ CNG 2024, factory-fitted CNG manual, 5 seats. Top-trim compact sedan with low running cost."},
    {"brand": "Tata", "model": "Altroz", "variant": "XE", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("685000.00"), "stock_quantity": 2, "description": "Altroz XE 2023, petrol manual, 5 seats. Premium hatchback with a wide cabin and planted ride."},
    {"brand": "Tata", "model": "Altroz", "variant": "XZ Diesel", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1055000.00"), "stock_quantity": 2, "description": "Altroz XZ Diesel 2024, diesel manual, 5 seats. Torquey premium hatchback for highway drivers."},
    {"brand": "Tata", "model": "Altroz", "variant": "XZ+ CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("995000.00"), "stock_quantity": 1, "description": "Altroz XZ+ CNG 2024, factory-fitted CNG manual, 5 seats. Premium hatchback with economical dual-fuel setup."},
    {"brand": "Tata", "model": "Punch", "variant": "Pure", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("715000.00"), "stock_quantity": 4, "description": "Punch Pure 2024, petrol manual, 5 seats. Micro-SUV with a tall stance and rugged appeal."},
    {"brand": "Tata", "model": "Punch", "variant": "Accomplished AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("975000.00"), "stock_quantity": 2, "description": "Punch Accomplished AMT 2024, petrol automated-manual, 5 seats. Feature-rich micro-SUV with automatic shifts."},
    {"brand": "Tata", "model": "Punch", "variant": "Creative CNG", "manufacturing_year": 2023, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1015000.00"), "stock_quantity": 1, "description": "Punch Creative CNG 2023, factory-fitted CNG manual, 5 seats. Micro-SUV with twin-cylinder CNG packaging."},
    {"brand": "Tata", "model": "Nexon", "variant": "Smart", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("825000.00"), "stock_quantity": 4, "description": "Nexon Smart 2024, petrol manual, 5 seats. Entry compact SUV with a strong safety body shell."},
    {"brand": "Tata", "model": "Nexon", "variant": "Pure Diesel", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1140000.00"), "stock_quantity": 3, "description": "Nexon Pure Diesel 2024, diesel manual, 5 seats. Efficient compact SUV for mixed city and highway use."},
    {"brand": "Tata", "model": "Nexon", "variant": "Creative DCT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1425000.00"), "stock_quantity": 2, "description": "Nexon Creative DCT 2024, petrol dual-clutch automatic, 5 seats. Sharp-looking compact SUV with quick shifts."},
    {"brand": "Tata", "model": "Nexon", "variant": "Fearless CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1395000.00"), "stock_quantity": 1, "description": "Nexon Fearless CNG 2024, factory-fitted CNG manual, 5 seats. Top compact SUV trim with low running cost."},
    {"brand": "Tata", "model": "Curvv", "variant": "Accomplished DCT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1750000.00"), "stock_quantity": 2, "description": "Curvv Accomplished DCT 2024, petrol dual-clutch automatic, 5 seats. Coupe-SUV with a modern connected cabin."},
    {"brand": "Tata", "model": "Curvv", "variant": "Empowered Diesel", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1995000.00"), "stock_quantity": 1, "description": "Curvv Empowered Diesel 2024, diesel automatic, 5 seats. Flagship coupe-SUV for relaxed long-distance cruising."},
    {"brand": "Tata", "model": "Harrier", "variant": "Pure", "manufacturing_year": 2023, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1695000.00"), "stock_quantity": 2, "description": "Harrier Pure 2023, diesel manual, 5 seats. Bold midsize SUV with a commanding road presence."},
    {"brand": "Tata", "model": "Harrier", "variant": "Fearless AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("2695000.00"), "stock_quantity": 1, "description": "Harrier Fearless AT 2024, diesel automatic, 5 seats. Fully loaded midsize SUV with premium cabin tech."},
    {"brand": "Tata", "model": "Tiago EV", "variant": "XZ+ Long Range", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1045000.00"), "stock_quantity": 2, "description": "Tiago EV XZ+ Long Range 2024, electric automatic, 5 seats. Affordable city EV with zippy instant torque."},
    {"brand": "Tata", "model": "Nexon EV", "variant": "Creative+ 45", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1595000.00"), "stock_quantity": 2, "description": "Nexon EV Creative+ 45 2024, electric automatic, 5 seats. Long-range electric SUV for city and weekend trips."},
    # ---------------- Mahindra (16) ----------------
    {"brand": "Mahindra", "model": "XUV 3XO", "variant": "MX1", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 3, "description": "XUV 3XO MX1 2024, petrol manual, 5 seats. Entry compact SUV with a refined turbo-petrol engine."},
    {"brand": "Mahindra", "model": "XUV 3XO", "variant": "AX5", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1245000.00"), "stock_quantity": 2, "description": "XUV 3XO AX5 2024, petrol automatic, 5 seats. Feature-rich compact SUV with a panoramic sunroof."},
    {"brand": "Mahindra", "model": "XUV 3XO", "variant": "AX7 Diesel AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1545000.00"), "stock_quantity": 1, "description": "XUV 3XO AX7 Diesel AT 2024, diesel automatic, 5 seats. Top compact SUV with strong low-end pull."},
    {"brand": "Mahindra", "model": "Thar", "variant": "LX", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 4, "price": Decimal("1495000.00"), "stock_quantity": 2, "description": "Thar LX 2023, petrol manual, 4 seats. Iconic off-roader with convertible-top lifestyle appeal."},
    {"brand": "Mahindra", "model": "Thar Roxx", "variant": "MX3", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1695000.00"), "stock_quantity": 3, "description": "Thar Roxx MX3 2024, diesel manual, 5 seats. Five-door off-roader with proper rear-door practicality."},
    {"brand": "Mahindra", "model": "Thar Roxx", "variant": "AX7L AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("2245000.00"), "stock_quantity": 1, "description": "Thar Roxx AX7L AT 2024, diesel automatic, 5 seats. Flagship five-door off-roader with premium cabin."},
    {"brand": "Mahindra", "model": "Scorpio", "variant": "Classic S", "manufacturing_year": 2023, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1395000.00"), "stock_quantity": 2, "description": "Scorpio Classic S 2023, diesel manual, 7 seats. Rugged ladder-frame SUV loved in semi-urban markets."},
    {"brand": "Mahindra", "model": "Scorpio-N", "variant": "Z4", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1845000.00"), "stock_quantity": 3, "description": "Scorpio-N Z4 2024, diesel manual, 7 seats. Big seven-seat SUV with true blue-blooded SUV character."},
    {"brand": "Mahindra", "model": "Scorpio-N", "variant": "Z8 Petrol AT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("2145000.00"), "stock_quantity": 1, "description": "Scorpio-N Z8 Petrol AT 2024, petrol automatic, 7 seats. Smooth seven-seat SUV with effortless auto shifts."},
    {"brand": "Mahindra", "model": "XUV700", "variant": "AX3", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1595000.00"), "stock_quantity": 2, "description": "XUV700 AX3 2023, petrol manual, 7 seats. Tech-loaded seven-seat SUV with a powerful engine."},
    {"brand": "Mahindra", "model": "XUV700", "variant": "AX7 Diesel AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("2545000.00"), "stock_quantity": 2, "description": "XUV700 AX7 Diesel AT 2024, diesel automatic, 7 seats. Premium seven-seater with relaxed highway manners."},
    {"brand": "Mahindra", "model": "XUV700", "variant": "AX7 L Diesel AT", "manufacturing_year": 2025, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("2795000.00"), "stock_quantity": 0, "description": "XUV700 AX7 L Diesel AT 2025, diesel automatic, 7 seats. Fully loaded flagship variant, currently out of stock."},
    {"brand": "Mahindra", "model": "Bolero", "variant": "B4", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("990000.00"), "stock_quantity": 3, "description": "Bolero B4 2024, diesel manual, 7 seats. Tough workhorse SUV built for rough roads and full loads."},
    {"brand": "Mahindra", "model": "Bolero Neo", "variant": "N4", "manufacturing_year": 2023, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("995000.00"), "stock_quantity": 2, "description": "Bolero Neo N4 2023, diesel manual, 7 seats. Compact seven-seat SUV with rugged underpinnings."},
    {"brand": "Mahindra", "model": "XUV400", "variant": "EC Pro", "manufacturing_year": 2023, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1645000.00"), "stock_quantity": 0, "description": "XUV400 EC Pro 2023, electric automatic, 5 seats. Long-range electric SUV, currently out of stock."},
    {"brand": "Mahindra", "model": "Bolero Neo", "variant": "N8", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1215000.00"), "stock_quantity": 1, "description": "Bolero Neo N8 2024, diesel manual, 7 seats. Top-trim rugged SUV with refined cabin touches."},
    # ---------------- Toyota (11) ----------------
    {"brand": "Toyota", "model": "Glanza", "variant": "E", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("695000.00"), "stock_quantity": 2, "description": "Glanza E 2023, petrol manual, 5 seats. Refined premium hatchback with Toyota service assurance."},
    {"brand": "Toyota", "model": "Glanza", "variant": "G AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("895000.00"), "stock_quantity": 2, "description": "Glanza G AMT 2024, petrol automated-manual, 5 seats. Smooth hatchback with automatic convenience."},
    {"brand": "Toyota", "model": "Glanza", "variant": "S CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("955000.00"), "stock_quantity": 1, "description": "Glanza S CNG 2024, factory-fitted CNG manual, 5 seats. Premium hatchback with economical running."},
    {"brand": "Toyota", "model": "Urban Cruiser Hyryder", "variant": "E", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1115000.00"), "stock_quantity": 2, "description": "Urban Cruiser Hyryder E 2023, petrol manual, 5 seats. Midsize SUV with Toyota reliability and space."},
    {"brand": "Toyota", "model": "Urban Cruiser Hyryder", "variant": "V Hybrid", "manufacturing_year": 2024, "fuel_type": "HYBRID", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1895000.00"), "stock_quantity": 2, "description": "Urban Cruiser Hyryder V Hybrid 2024, strong-hybrid automatic, 5 seats. Very efficient midsize SUV for city use."},
    {"brand": "Toyota", "model": "Rumion", "variant": "S", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1075000.00"), "stock_quantity": 2, "description": "Rumion S 2024, petrol manual, 7 seats. Practical seven-seat MPV with sliding-door flexibility."},
    {"brand": "Toyota", "model": "Rumion", "variant": "V CNG", "manufacturing_year": 2024, "fuel_type": "CNG", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1245000.00"), "stock_quantity": 1, "description": "Rumion V CNG 2024, factory-fitted CNG manual, 7 seats. Seven-seat MPV with low family running costs."},
    {"brand": "Toyota", "model": "Innova Crysta", "variant": "GX", "manufacturing_year": 2023, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1995000.00"), "stock_quantity": 1, "description": "Innova Crysta GX 2023, diesel manual, 7 seats. Legendary seven-seat MPV with unmatched comfort."},
    {"brand": "Toyota", "model": "Innova HyCross", "variant": "VX Hybrid", "manufacturing_year": 2024, "fuel_type": "HYBRID", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("3050000.00"), "stock_quantity": 1, "description": "Innova HyCross VX Hybrid 2024, strong-hybrid automatic, 7 seats. Premium MPV with serene long-drive comfort."},
    {"brand": "Toyota", "model": "Fortuner", "variant": "2.8 4x2 MT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("3545000.00"), "stock_quantity": 1, "description": "Fortuner 2.8 4x2 MT 2024, diesel manual, 7 seats. Ladder-frame SUV with go-anywhere ability."},
    {"brand": "Toyota", "model": "Fortuner", "variant": "GR-S", "manufacturing_year": 2025, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("5245000.00"), "stock_quantity": 1, "description": "Fortuner GR-S 2025, diesel automatic, 7 seats. Sport-styled flagship SUV with commanding presence."},
    # ---------------- Honda (8) ----------------
    {"brand": "Honda", "model": "Amaze", "variant": "S", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 3, "description": "Amaze S 2024, petrol manual, 5 seats. Refined compact sedan with Honda engine smoothness."},
    {"brand": "Honda", "model": "Amaze", "variant": "ZX CVT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1095000.00"), "stock_quantity": 2, "description": "Amaze ZX CVT 2024, petrol continuously-variable automatic, 5 seats. Top compact sedan with seamless auto shifts."},
    {"brand": "Honda", "model": "City", "variant": "SV", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1195000.00"), "stock_quantity": 2, "description": "City SV 2023, petrol manual, 5 seats. Benchmark sedan with a roomy cabin and slick gearbox."},
    {"brand": "Honda", "model": "City", "variant": "V CVT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1395000.00"), "stock_quantity": 3, "description": "City V CVT 2024, petrol continuously-variable automatic, 5 seats. Effortless sedan for city and highway."},
    {"brand": "Honda", "model": "City", "variant": "ZX Hybrid eHEV", "manufacturing_year": 2024, "fuel_type": "HYBRID", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1995000.00"), "stock_quantity": 1, "description": "City ZX Hybrid eHEV 2024, strong-hybrid automatic, 5 seats. Highly efficient sedan with advanced hybrid tech."},
    {"brand": "Honda", "model": "Elevate", "variant": "SV", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1145000.00"), "stock_quantity": 2, "description": "Elevate SV 2023, petrol manual, 5 seats. Spacious Honda SUV with a practical cabin layout."},
    {"brand": "Honda", "model": "Elevate", "variant": "VX CVT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1545000.00"), "stock_quantity": 2, "description": "Elevate VX CVT 2024, petrol continuously-variable automatic, 5 seats. Family SUV with smooth auto driving."},
    {"brand": "Honda", "model": "Elevate", "variant": "ZX CVT", "manufacturing_year": 2025, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1675000.00"), "stock_quantity": 0, "description": "Elevate ZX CVT 2025, petrol continuously-variable automatic, 5 seats. Flagship SUV trim, currently out of stock."},
    # ---------------- Kia (11) ----------------
    {"brand": "Kia", "model": "Sonet", "variant": "HTE", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("795000.00"), "stock_quantity": 3, "description": "Sonet HTE 2023, petrol manual, 5 seats. Compact SUV with youthful styling and connected tech."},
    {"brand": "Kia", "model": "Sonet", "variant": "HTK+ Diesel", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1195000.00"), "stock_quantity": 2, "description": "Sonet HTK+ Diesel 2024, diesel manual, 5 seats. Torquey compact SUV for confident highway runs."},
    {"brand": "Kia", "model": "Sonet", "variant": "GTX+ DCT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1545000.00"), "stock_quantity": 1, "description": "Sonet GTX+ DCT 2024, petrol dual-clutch automatic, 5 seats. Sporty turbo compact SUV, fully loaded."},
    {"brand": "Kia", "model": "Seltos", "variant": "HTE", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1105000.00"), "stock_quantity": 2, "description": "Seltos HTE 2023, petrol manual, 5 seats. Popular midsize SUV with premium road manners."},
    {"brand": "Kia", "model": "Seltos", "variant": "HTX Diesel AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1845000.00"), "stock_quantity": 2, "description": "Seltos HTX Diesel AT 2024, diesel automatic, 5 seats. Refined SUV with relaxed automatic cruising."},
    {"brand": "Kia", "model": "Seltos", "variant": "X-Line DCT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1995000.00"), "stock_quantity": 1, "description": "Seltos X-Line DCT 2024, petrol dual-clutch automatic, 5 seats. Matte-finished flagship with turbo punch."},
    {"brand": "Kia", "model": "Carens", "variant": "Premium", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("1045000.00"), "stock_quantity": 3, "description": "Carens Premium 2023, petrol manual, 7 seats. Value seven-seat MPV with car-like driving ease."},
    {"brand": "Kia", "model": "Carens", "variant": "Prestige+ Diesel AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("1745000.00"), "stock_quantity": 2, "description": "Carens Prestige+ Diesel AT 2024, diesel automatic, 7 seats. Family MPV with effortless long-trip ability."},
    {"brand": "Kia", "model": "Carens", "variant": "Luxury+ DCT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 6, "price": Decimal("1945000.00"), "stock_quantity": 1, "description": "Carens Luxury+ DCT 2024, petrol dual-clutch automatic, 6 seats. Six-seat MPV with captain chairs."},
    {"brand": "Kia", "model": "Carnival", "variant": "Limousine+", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("6420000.00"), "stock_quantity": 1, "description": "Carnival Limousine+ 2024, diesel automatic, 7 seats. Luxury lounge-on-wheels MPV with VIP second row."},
    {"brand": "Kia", "model": "Sonet", "variant": "HTK Diesel AT", "manufacturing_year": 2025, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1345000.00"), "stock_quantity": 0, "description": "Sonet HTK Diesel AT 2025, diesel automatic, 5 seats. Easy-driving diesel compact SUV, currently out of stock."},
    # ---------------- Renault (6) ----------------
    {"brand": "Renault", "model": "Kwid", "variant": "RXE", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("479000.00"), "stock_quantity": 4, "description": "Kwid RXE 2023, petrol manual, 5 seats. SUV-styled hatchback, great value first car."},
    {"brand": "Renault", "model": "Kwid", "variant": "Climber AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("645000.00"), "stock_quantity": 2, "description": "Kwid Climber AMT 2024, petrol automated-manual, 5 seats. Rugged-styled hatchback with automatic ease."},
    {"brand": "Renault", "model": "Triber", "variant": "RXL", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("645000.00"), "stock_quantity": 3, "description": "Triber RXL 2023, petrol manual, 7 seats. Modular seven-seat MPV with removable third row."},
    {"brand": "Renault", "model": "Triber", "variant": "RXT AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 7, "price": Decimal("845000.00"), "stock_quantity": 2, "description": "Triber RXT AMT 2024, petrol automated-manual, 7 seats. Flexible seven-seater with automatic convenience."},
    {"brand": "Renault", "model": "Kiger", "variant": "RXL", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("645000.00"), "stock_quantity": 2, "description": "Kiger RXL 2023, petrol manual, 5 seats. Sporty compact SUV with good cabin space."},
    {"brand": "Renault", "model": "Kiger", "variant": "RXT CVT Turbo", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("995000.00"), "stock_quantity": 2, "description": "Kiger RXT CVT Turbo 2024, petrol continuously-variable automatic, 5 seats. Turbo compact SUV with smooth auto."},
    # ---------------- Nissan (3) ----------------
    {"brand": "Nissan", "model": "Magnite", "variant": "XE", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("615000.00"), "stock_quantity": 3, "description": "Magnite XE 2023, petrol manual, 5 seats. Big-on-value compact SUV with bold styling."},
    {"brand": "Nissan", "model": "Magnite", "variant": "Acenta AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("845000.00"), "stock_quantity": 2, "description": "Magnite Acenta AMT 2024, petrol automated-manual, 5 seats. Value compact SUV with automatic comfort."},
    {"brand": "Nissan", "model": "Magnite", "variant": "Tekna CVT Turbo", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1045000.00"), "stock_quantity": 1, "description": "Magnite Tekna CVT Turbo 2024, petrol continuously-variable automatic, 5 seats. Top turbo SUV with smooth auto."},
    # ---------------- Volkswagen (5) ----------------
    {"brand": "Volkswagen", "model": "Taigun", "variant": "Comfortline", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1145000.00"), "stock_quantity": 2, "description": "Taigun Comfortline 2023, petrol manual, 5 seats. German-engineered SUV with solid build quality."},
    {"brand": "Volkswagen", "model": "Taigun", "variant": "Highline", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1445000.00"), "stock_quantity": 2, "description": "Taigun Highline 2024, petrol manual, 5 seats. Balanced SUV with crisp handling and a neat cabin."},
    {"brand": "Volkswagen", "model": "Taigun", "variant": "GT DSG", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1845000.00"), "stock_quantity": 1, "description": "Taigun GT DSG 2024, petrol dual-clutch automatic, 5 seats. Enthusiast SUV with rapid gearshifts."},
    {"brand": "Volkswagen", "model": "Tiguan", "variant": "Elegance", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("3545000.00"), "stock_quantity": 1, "description": "Tiguan Elegance 2024, petrol automatic, 5 seats. Premium German SUV with all-weather capability."},
    {"brand": "Volkswagen", "model": "Virtus", "variant": "Highline", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1195000.00"), "stock_quantity": 2, "description": "Virtus Highline 2023, petrol manual, 5 seats. Long-wheelbase sedan with generous rear legroom."},
    # ---------------- Skoda (5) ----------------
    {"brand": "Skoda", "model": "Kushaq", "variant": "Active", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1095000.00"), "stock_quantity": 2, "description": "Kushaq Active 2023, petrol manual, 5 seats. Sturdy Czech SUV with a comfortable ride."},
    {"brand": "Skoda", "model": "Kushaq", "variant": "Ambition", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1445000.00"), "stock_quantity": 2, "description": "Kushaq Ambition 2024, petrol manual, 5 seats. Mid-trim SUV with a refined cabin and strong safety."},
    {"brand": "Skoda", "model": "Kushaq", "variant": "Style DSG", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "DCT", "seating_capacity": 5, "price": Decimal("1845000.00"), "stock_quantity": 1, "description": "Kushaq Style DSG 2024, petrol dual-clutch automatic, 5 seats. Flagship SUV with quick automatic shifts."},
    {"brand": "Skoda", "model": "Kodiaq", "variant": "Sportline", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("3945000.00"), "stock_quantity": 1, "description": "Kodiaq Sportline 2024, petrol automatic, 7 seats. Premium seven-seat SUV with a luxurious cabin."},
    {"brand": "Skoda", "model": "Slavia", "variant": "Signature", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1545000.00"), "stock_quantity": 2, "description": "Slavia Signature 2024, petrol manual, 5 seats. Elegant sedan with a big boot and airy cabin."},
    # ---------------- MG (9) ----------------
    {"brand": "MG", "model": "Comet EV", "variant": "Pace", "manufacturing_year": 2023, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("745000.00"), "stock_quantity": 2, "description": "Comet EV Pace 2023, electric automatic, 5 seats. Ultra-compact city EV, easy to park and run."},
    {"brand": "MG", "model": "Comet EV", "variant": "Exclusive", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("945000.00"), "stock_quantity": 2, "description": "Comet EV Exclusive 2024, electric automatic, 5 seats. Top city EV with connected-car features."},
    {"brand": "MG", "model": "Astor", "variant": "Sprint", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1045000.00"), "stock_quantity": 2, "description": "Astor Sprint 2023, petrol manual, 5 seats. Tech-forward SUV with a premium-feel cabin."},
    {"brand": "MG", "model": "Astor", "variant": "Sharp CVT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 5, "price": Decimal("1645000.00"), "stock_quantity": 1, "description": "Astor Sharp CVT 2024, petrol continuously-variable automatic, 5 seats. Loaded SUV with a smooth auto."},
    {"brand": "MG", "model": "Hector", "variant": "Shine", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1495000.00"), "stock_quantity": 2, "description": "Hector Shine 2023, petrol manual, 5 seats. Big bold SUV with massive cabin space."},
    {"brand": "MG", "model": "Hector", "variant": "Sharp Diesel", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("2145000.00"), "stock_quantity": 1, "description": "Hector Sharp Diesel 2024, diesel manual, 5 seats. Flagship diesel SUV for long family drives."},
    {"brand": "MG", "model": "Hector Plus", "variant": "Savvy CVT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "CVT", "seating_capacity": 6, "price": Decimal("2245000.00"), "stock_quantity": 1, "description": "Hector Plus Savvy CVT 2024, petrol continuously-variable automatic, 6 seats. Six-seat SUV with captain chairs."},
    {"brand": "MG", "model": "ZS EV", "variant": "Excite", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1895000.00"), "stock_quantity": 1, "description": "ZS EV Excite 2024, electric automatic, 5 seats. Proven electric SUV with refined road manners."},
    {"brand": "MG", "model": "Windsor EV", "variant": "Essence", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1595000.00"), "stock_quantity": 2, "description": "Windsor EV Essence 2024, electric automatic, 5 seats. Lounge-like electric crossover with strong range."},
    # ---------------- Citroen (5) ----------------
    {"brand": "Citroen", "model": "C3", "variant": "Live", "manufacturing_year": 2023, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("625000.00"), "stock_quantity": 2, "description": "C3 Live 2023, petrol manual, 5 seats. Quirky French hatchback with a famously soft ride."},
    {"brand": "Citroen", "model": "C3", "variant": "Feel AMT", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AMT", "seating_capacity": 5, "price": Decimal("845000.00"), "stock_quantity": 1, "description": "C3 Feel AMT 2024, petrol automated-manual, 5 seats. Comfortable hatchback with automatic ease."},
    {"brand": "Citroen", "model": "C3 Aircross", "variant": "Plus", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1045000.00"), "stock_quantity": 2, "description": "C3 Aircross Plus 2024, petrol manual, 5 seats. Roomy French SUV with modular seating."},
    {"brand": "Citroen", "model": "C3 Aircross", "variant": "Max AT 7-Seater", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("1495000.00"), "stock_quantity": 1, "description": "C3 Aircross Max AT 7-Seater 2024, petrol automatic, 7 seats. Seven-seat French SUV with auto comfort."},
    {"brand": "Citroen", "model": "eC3", "variant": "Feel", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1345000.00"), "stock_quantity": 1, "description": "eC3 Feel 2024, electric automatic, 5 seats. Simple practical electric hatchback for city use."},
    # ---------------- Jeep (5) ----------------
    {"brand": "Jeep", "model": "Compass", "variant": "Longitude", "manufacturing_year": 2023, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("2145000.00"), "stock_quantity": 1, "description": "Compass Longitude 2023, diesel manual, 5 seats. Authentic American SUV with solid build."},
    {"brand": "Jeep", "model": "Compass", "variant": "Model S 4x4 AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("2945000.00"), "stock_quantity": 1, "description": "Compass Model S 4x4 AT 2024, diesel automatic, 5 seats. Capable all-wheel-drive SUV, fully loaded."},
    {"brand": "Jeep", "model": "Meridian", "variant": "Limited", "manufacturing_year": 2023, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 7, "price": Decimal("2695000.00"), "stock_quantity": 1, "description": "Meridian Limited 2023, diesel manual, 7 seats. Premium seven-seat SUV with refined interiors."},
    {"brand": "Jeep", "model": "Meridian", "variant": "Overland 4x4 AT", "manufacturing_year": 2024, "fuel_type": "DIESEL", "transmission": "AUTOMATIC", "seating_capacity": 7, "price": Decimal("3645000.00"), "stock_quantity": 0, "description": "Meridian Overland 4x4 AT 2024, diesel automatic, 7 seats. Adventure-ready flagship, currently out of stock."},
    {"brand": "Jeep", "model": "Compass", "variant": "Night Eagle", "manufacturing_year": 2022, "fuel_type": "DIESEL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1995000.00"), "stock_quantity": 0, "description": "Compass Night Eagle 2022, diesel manual, 5 seats. Special-edition SUV, currently out of stock."},
    # ---------------- BYD (4) ----------------
    {"brand": "BYD", "model": "Atto 3", "variant": "Dynamic", "manufacturing_year": 2023, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("2595000.00"), "stock_quantity": 1, "description": "Atto 3 Dynamic 2023, electric automatic, 5 seats. Blade-battery electric SUV with a tech-rich cabin."},
    {"brand": "BYD", "model": "Atto 3", "variant": "Superior", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("2995000.00"), "stock_quantity": 1, "description": "Atto 3 Superior 2024, electric automatic, 5 seats. Long-range electric SUV with premium finishes."},
    {"brand": "BYD", "model": "Seal", "variant": "Premium", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("4695000.00"), "stock_quantity": 1, "description": "Seal Premium 2024, electric automatic, 5 seats. Sleek electric sedan with sports-car pace."},
    {"brand": "BYD", "model": "e6", "variant": "GL", "manufacturing_year": 2023, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("2915000.00"), "stock_quantity": 0, "description": "e6 GL 2023, electric automatic, 5 seats. Spacious electric MPV, currently out of stock."},
    # ---------------- Extra coverage (2) ----------------
    {"brand": "Tata", "model": "Punch EV", "variant": "Adventure Long Range", "manufacturing_year": 2024, "fuel_type": "ELECTRIC", "transmission": "AUTOMATIC", "seating_capacity": 5, "price": Decimal("1245000.00"), "stock_quantity": 2, "description": "Punch EV Adventure Long Range 2024, electric automatic, 5 seats. Practical electric micro-SUV for the city."},
    {"brand": "Hyundai", "model": "Creta", "variant": "Knight", "manufacturing_year": 2024, "fuel_type": "PETROL", "transmission": "MANUAL", "seating_capacity": 5, "price": Decimal("1445000.00"), "stock_quantity": 2, "description": "Creta Knight 2024, petrol manual, 5 seats. Blacked-out special edition of the popular compact SUV."},
]


class Command(BaseCommand):
    help = "Seed ~150 realistic Indian-market demo vehicles (idempotent, additive-only)."

    def add_arguments(self, parser):
        parser.add_argument(
            "--dealership-id",
            type=int,
            default=None,
            help="Existing dealership id to seed (verified, never created).",
        )

    def handle(self, *args, **options):
        dealership = self._resolve_dealership(options)
        created = 0
        skipped = 0
        for entry in DEMO_VEHICLES:
            unique_lookup = {
                "dealership": dealership,
                "brand": entry["brand"],
                "model": entry["model"],
                "variant": entry["variant"],
                "manufacturing_year": entry["manufacturing_year"],
            }
            if Vehicle.objects.filter(**unique_lookup).exists():
                skipped += 1
                continue
            Vehicle.objects.create(
                **unique_lookup,
                fuel_type=entry["fuel_type"],
                transmission=entry["transmission"],
                seating_capacity=entry["seating_capacity"],
                price=entry["price"],
                description=entry["description"],
                stock_quantity=entry["stock_quantity"],
                is_available=entry["stock_quantity"] > 0,
            )
            created += 1
        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created} new vehicle(s) for {dealership.name} "
                f"(id={dealership.pk}). Skipped {skipped} existing row(s); "
                f"{len(DEMO_VEHICLES)} vehicles in the demo seed set, "
                "existing rows untouched."
            )
        )

    def _resolve_dealership(self, options):
        if options.get("dealership_id"):
            try:
                return Dealership.objects.get(pk=options["dealership_id"])
            except Dealership.DoesNotExist:
                raise CommandError(
                    f"Dealership {options['dealership_id']} does not exist. "
                    "Refusing to create one automatically."
                )
        active = list(Dealership.objects.filter(is_active=True).order_by("pk"))
        if not active:
            raise CommandError("No active dealership exists. Pass --dealership-id.")
        if len(active) > 1:
            raise CommandError("Multiple dealerships exist. Pass --dealership-id.")
        return active[0]
